# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 12.0.0.0b3.dev317\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-08-12 06:31+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova/filters.py:80
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr ""

#: nova/service.py:155
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr ""

#: nova/wsgi.py:154
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:258
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:278
msgid "WSGI server has stopped."
msgstr ""

#: nova/api/ec2/__init__.py:466
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: nova/api/ec2/cloud.py:417
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:460
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:472
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:485
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:788
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:861
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:865 nova/api/openstack/compute/contrib/volumes.py:166
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:905
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: nova/api/ec2/cloud.py:935 nova/api/openstack/compute/contrib/volumes.py:395
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:1302
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:1307
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1312
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1345
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1498
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:1613
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1649
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1718
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/ec2utils.py:292
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/openstack/__init__.py:105
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:335
msgid "V3 API has been disabled by configuration"
msgstr ""

#: nova/api/openstack/__init__.py:380
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:531
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:534
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:53
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:56
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/contrib/volumes.py:504
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:72
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:154
#, python-format
msgid "Detach interface %s"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:160
#: nova/api/openstack/compute/plugins/v3/hosts.py:139
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:183
#: nova/api/openstack/compute/plugins/v3/hosts.py:160
#, python-format
msgid "Enabling host %s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:185
#: nova/api/openstack/compute/plugins/v3/hosts.py:162
#, python-format
msgid "Disabling host %s."
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:98
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:86
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:77
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:111
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:298
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:542
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/cells/messaging.py:1099
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, "
"updated_since=%(since_str)s"
msgstr ""

#: nova/cells/scheduler.py:239
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s "
"second(s)"
msgstr ""

#: nova/cells/filters/target_cell.py:59
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler "
"hint"
msgstr ""

#: nova/compute/api.py:1524
msgid "instance termination disabled"
msgstr ""

#: nova/compute/api.py:1537
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1607
msgid "Instance is already in deleting state, ignoring this request"
msgstr ""

#: nova/compute/api.py:1652
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: "
"%(status)s"
msgstr ""

#: nova/compute/api.py:1662
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1679
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1735
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/api.py:2261
#, python-format
msgid "Skipping quiescing instance: %(reason)s."
msgstr ""

#: nova/compute/api.py:3916
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:4021
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/claims.py:167
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:236
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:243
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:250
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""

#: nova/compute/manager.py:313
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:808
msgid "Deleting instance as it has been evacuated from this host"
msgstr ""

#: nova/compute/manager.py:820
msgid "Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""

#: nova/compute/manager.py:996
msgid ""
"Service started deleting the instance during the previous run, but did "
"not finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1117
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""

#: nova/compute/manager.py:1139
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:1189
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:1254
msgid ""
"Instance lifecycle events from the compute driver have been disabled. "
"Note that lifecycle changes to an instance outside of the compute service"
" will only be synchronized by the _sync_power_states periodic task."
msgstr ""

#: nova/compute/manager.py:1860
msgid "Starting instance..."
msgstr ""

#: nova/compute/manager.py:2205
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:2371
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2415
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""

#: nova/compute/manager.py:2596
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:2620
msgid "disk on shared storage, recreating using existing disk"
msgstr ""

#: nova/compute/manager.py:2624
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:2718
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:2749
#, python-format
msgid "Detaching from volume api: %s"
msgstr ""

#: nova/compute/manager.py:2776
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:2914
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:3048
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:3096
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3131
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:3179
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:3256
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3277
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3468
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:3522
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:3875
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:3891
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:3928 nova/compute/manager.py:3945
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:3984
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:4218
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:4482
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:4507
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:4684
#, python-format
msgid "Swapping volume %(old_volume)s for %(new_volume)s"
msgstr ""

#: nova/compute/manager.py:5041
msgid "_post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:5123
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5125
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:5162
msgid "Post operation of migration started"
msgstr ""

#: nova/compute/manager.py:5439
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/compute/manager.py:5454
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:5508
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5558
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""

#: nova/compute/manager.py:5605
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:5786 nova/compute/manager.py:5843
#, python-format
msgid "During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""

#: nova/compute/manager.py:5830
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to"
" host %(dst)s"
msgstr ""

#: nova/compute/manager.py:5851
#, python-format
msgid ""
"During _sync_instance_power_state the DB power_state (%(db_power_state)s)"
" does not match the vm_power_state from the hypervisor "
"(%(vm_power_state)s). Updating power_state in the DB to match the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:5998
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:6032
#, python-format
msgid "Compute node '%s' not found in update_available_resource."
msgstr ""

#: nova/compute/manager.py:6050
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6100
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but"
" still present on host."
msgstr ""

#: nova/compute/manager.py:6118
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6166
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6176
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr ""

#: nova/compute/resource_tracker.py:333
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:379
#, python-format
msgid "Auditing locally available compute resources for node %(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:386
msgid ""
"Virt driver does not support 'get_available_resource'. Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:485
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:558
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:566
#, python-format
msgid ""
"Final resource view: name=%(node)s phys_ram=%(phys_ram)sMB "
"used_ram=%(used_ram)sMB phys_disk=%(phys_disk)sGB "
"used_disk=%(used_disk)sGB total_vcpus=%(total_vcpus)s "
"used_vcpus=%(used_vcpus)s pci_stats=%(pci_stats)s"
msgstr ""

#: nova/compute/resource_tracker.py:632
#, python-format
msgid "Updating from migration %s"
msgstr ""

#: nova/conductor/api.py:189
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/consoleauth/manager.py:100
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:125
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:3460
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:5284
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must "
"have been rebooted or crashed. Updating totals."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:36
msgid ""
"Skipped adding instances_project_id_deleted_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:40
#: nova/db/sqlalchemy/migrate_repo/versions/295_add_virtual_interfaces_uuid_index.py:40
#, python-format
msgid "Skipped adding %s because an equivalent index already exists."
msgstr ""

#: nova/image/glance.py:350
#, python-format
msgid "Successfully transferred using %s"
msgstr ""

#: nova/image/s3.py:385
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:163
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:225 nova/network/neutronv2/api.py:1196
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr ""

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr ""

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:335
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:508
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:571
#, python-format
msgid "Network deallocated for instance (fixed ips: '%s')"
msgstr ""

#: nova/network/manager.py:1037
#, python-format
msgid "Unable to release %s because vif doesn't exist"
msgstr ""

#: nova/network/manager.py:1044
#, python-format
msgid "Unable to release %s because vif object doesn't exist"
msgstr ""

#: nova/network/manager.py:1131
#, python-format
msgid ""
"Ignoring request to release fixed IP %(address)s with MAC %(mac)s since "
"it is now associated with a new instance that is in the process of "
"allocating it's network."
msgstr ""

#: nova/network/minidns.py:201
#, python-format
msgid "deleted %s"
msgstr ""

#: nova/network/neutronv2/api.py:1673
#, python-format
msgid ""
"Port %s from network info_cache is no longer associated with instance in "
"Neutron. Removing from network info_cache."
msgstr ""

#: nova/network/security_group/neutron_driver.py:464
#: nova/network/security_group/neutron_driver.py:519
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr ""

#: nova/scheduler/host_manager.py:574
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""

#: nova/scheduler/host_manager.py:636
#, python-format
msgid "Received an update from an unknown host '%s'. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:654
#, python-format
msgid ""
"Received a delete update from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:672
#, python-format
msgid ""
"The instance sync for host '%s' did not match. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:676
#, python-format
msgid "Successfully synced instances from host '%s'."
msgstr ""

#: nova/scheduler/host_manager.py:680
#, python-format
msgid ""
"Received a sync request from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/filters/utils.py:63
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""

#: nova/virt/block_device.py:225
#, python-format
msgid "preserve multipath_id %s"
msgstr ""

#: nova/virt/block_device.py:447
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/driver.py:1450
#, python-format
msgid "Loading compute driver '%s'"
msgstr ""

#: nova/virt/firewall.py:173 nova/virt/libvirt/firewall.py:363
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/firewall.py:443
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr ""

#: nova/virt/disk/mount/api.py:160
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr ""

#: nova/virt/disk/mount/loop.py:35
#, python-format
msgid "Loop mount error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:92 nova/virt/disk/mount/nbd.py:105
#, python-format
msgid "NBD mount error: %s"
msgstr ""

#: nova/virt/disk/vfs/api.py:72
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/basevolumeutils.py:75
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr ""

#: nova/virt/hyperv/vmops.py:260
msgid "Spawning new instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:380 nova/virt/vmwareapi/vmops.py:763
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:394 nova/virt/libvirt/driver.py:2970
#, python-format
msgid "Creating config drive at %(path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:444
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:496
msgid "Soft shutdown succeeded."
msgstr ""

#: nova/virt/ironic/driver.py:764
#, python-format
msgid "Config drive for instance %(instance)s on baremetal node %(node)s created."
msgstr ""

#: nova/virt/ironic/driver.py:788
#, python-format
msgid "Successfully provisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:885
#, python-format
msgid "Successfully unprovisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:917
#, python-format
msgid "Successfully rebooted Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:942
#, python-format
msgid "Successfully powered off Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:968
#, python-format
msgid "Successfully powered on Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:1171
msgid "Instance was successfully rebuilt"
msgstr ""

#: nova/virt/libvirt/driver.py:579
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:805
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:810
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:820
msgid "Instance may be started again."
msgstr ""

#: nova/virt/libvirt/driver.py:830
msgid "Going to destroy instance again."
msgstr ""

#: nova/virt/libvirt/driver.py:1434
msgid "Beginning live snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1437
msgid "Beginning cold snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1468
msgid "Snapshot extracted, beginning image upload"
msgstr ""

#: nova/virt/libvirt/driver.py:1480
msgid "Snapshot image upload complete"
msgstr ""

#: nova/virt/libvirt/driver.py:2074
msgid "Instance soft rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2127
msgid "Instance shutdown successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2135
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr ""

#: nova/virt/libvirt/driver.py:2199
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2250
msgid "Instance already shutdown."
msgstr ""

#: nova/virt/libvirt/driver.py:2271
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2300
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2485
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2501
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: nova/virt/libvirt/driver.py:2537
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2548 nova/virt/libvirt/driver.py:2575
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr ""

#: nova/virt/libvirt/driver.py:2834
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/driver.py:2961
msgid "Using config drive"
msgstr ""

#: nova/virt/libvirt/driver.py:3754
msgid "Configuring timezone for windows instance to localtime"
msgstr ""

#: nova/virt/libvirt/driver.py:4977
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. "
"Instance=%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4984
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats "
"for device"
msgstr ""

#: nova/virt/libvirt/driver.py:5317
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5802
#, python-format
msgid "Error %(ex)s, migration failed"
msgstr ""

#: nova/virt/libvirt/driver.py:5855
#, python-format
msgid "Increasing downtime to %(downtime)dms after %(waittime)d sec elapsed time"
msgstr ""

#: nova/virt/libvirt/driver.py:5897
#, python-format
msgid ""
"Migration running for %(secs)d secs, memory %(remaining)d%% remaining; "
"(bytes processed=%(processed_memory)d, remaining=%(remaining_memory)d, "
"total=%(total_memory)d)"
msgstr ""

#: nova/virt/libvirt/driver.py:5907
#, python-format
msgid ""
"Data remaining %(remaining)d bytes, low watermark %(watermark)d bytes "
"%(last)d seconds ago"
msgstr ""

#: nova/virt/libvirt/driver.py:5917
msgid "Migration operation has completed"
msgstr ""

#: nova/virt/libvirt/driver.py:6685
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:7062
#, python-format
msgid "Deleting instance files %s"
msgstr ""

#: nova/virt/libvirt/driver.py:7075
#, python-format
msgid "Deletion of %s failed"
msgstr ""

#: nova/virt/libvirt/driver.py:7079
#, python-format
msgid "Deletion of %s complete"
msgstr ""

#: nova/virt/libvirt/firewall.py:117
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:125
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:289
#, python-format
msgid "Failed to undefine network filter %(name)s. Try %(cnt)d of %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/host.py:717
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: "
"%(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:767
#, python-format
msgid "Libvirt host capabilities %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:430
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:193
#, python-format
msgid "Writing stored info to %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:416
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash "
"stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:425
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr ""

#: nova/virt/libvirt/imagecache.py:454
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:457
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:507
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:530
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""

#: nova/virt/libvirt/imagecache.py:613
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:616
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:620
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:149
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:473
msgid "findmnt tool is not installed"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:66
#, python-format
msgid "Mounted volume: %s"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:134
#, python-format
msgid "Fixing previous mount %s which was not unmounted correctly."
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:156
#, python-format
msgid "Trying to disconnected unmounted volume at %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:220
#, python-format
msgid "VMware vCenter version: %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:513
#, python-format
msgid "Invalid cluster or resource pool name : %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:261
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:279
#, python-format
msgid "Copied virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:293
#, python-format
msgid "Deleted virtual disk %s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:381
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:384 nova/virt/vmwareapi/images.py:455
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/images.py:450
#, python-format
msgid "Downloaded OVA image file %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1384
msgid "Destroyed the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:867
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1416 nova/virt/xenapi/vmops.py:1709
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1420 nova/virt/xenapi/vmops.py:1713
msgid "Automatically hard rebooting"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:454
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate "
"backing disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/host.py:76
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skip ping migration to a new host"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:397
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:400
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt "
"%(num_attempt)d/%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:687
#, python-format
msgid "Deleted %s snapshots."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1330
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2178
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2474
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2483
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1295
msgid "Starting halted instance found during reboot"
msgstr ""

#: nova/virt/xenapi/vmops.py:1499
msgid "Destroying VM"
msgstr ""

#: nova/virt/xenapi/volumeops.py:64
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:127
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:149
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: nova/vnc/xvp_proxy.py:94
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:100
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:115
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:135
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:138
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:148
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:155
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:175
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/encryptors/luks.py:110
#, python-format
msgid "%s is not a valid LUKS device; formatting device for first use"
msgstr ""

